//
//  PersonalityProfile.swift
//  Companion
//
//  Aggregated personality profile computed from memories and conversations
//

import Foundation
import SwiftData

@Model
final class PersonalityProfile {
    var id: UUID
    var updatedAt: Date
    
    // Big Five traits (computed from memories/conversations)
    var openness: Double?
    var conscientiousness: Double?
    var extraversion: Double?
    var agreeableness: Double?
    var neuroticism: Double?
    
    // Custom traits specific to user
    var customTraits: [String: Double]  // trait name -> strength (0.0-1.0)
    
    // Summary generated by LLM
    var summary: String?
    var summaryGeneratedAt: Date?
    
    init() {
        self.id = UUID()
        self.updatedAt = Date()
        self.customTraits = [:]
    }
}
